/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.elite.cdr.validator.Asn1Types;

import com.beanit.jasn1.ber.types.BerOctetString;


public class AddressString extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public AddressString() {
	}

	public AddressString(byte[] value) {
		super(value);
	}

}
